version: "3.8"
services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      KAKAO_CLIENT_ID: "${Client_ID}"
      PASSWORD: "${PASSWORD}"
      URL: "${URL}"
      USERNAME: "${USERNAME}"
<<<<<<< HEAD
=======
    depends_on:
      - redis

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379
    command: ["redis-server", "--appendonly", "yes"]
>>>>>>> 2961f0b (refactor: kakao login)

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - spring
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      KAKAO_CLIENT_ID: "${Client_ID}"
      PASSWORD: "${PASSWORD}"
      URL: "${URL}"
      USERNAME: "${USERNAME}"
      SERVER_PORT: 80

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: >
#      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
#      --email jy8294@naver.com --agree-tos --no-eff-email
#      -d snapmeal.store -d www.snapmeal.store"

volumes:
  redis_data:
